/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author user
 */
public class DataPengeluaran extends javax.swing.JFrame {
    public static Connection conn;
    public static Statement stm;
    public static ResultSet rs;
    public static PreparedStatement psht;
    private JTextField textField;
    private String defaultText = "Masukkan Tanggal Pengeluaran";

    /**
     * Creates new form DataPengeluaran
     */
    public DataPengeluaran() {
        initComponents();
        tampiltabel();
        koneksimysql();
        
        textField = new JTextField();
        txtcari.setText(defaultText);
        txtcari.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent fe) {
                if (txtcari.getText().equals(defaultText)){
                    txtcari.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent fe) {
                if (txtcari.getText().isEmpty()){
                    txtcari.setText(defaultText);
                }
            }
        });
        
    }

 public void tampiltabel(){
        koneksimysql();
        DefaultTableModel tb = new DefaultTableModel();
        //judul kolom
        tb.addColumn("No");
        tb.addColumn("Tanggal Pengeluaran");
        tb.addColumn("Tagihan Listrik");
        tb.addColumn("Tagihan Air"); 
        tb.addColumn("Kebutuhan Fasilitas");
        tb.addColumn("Total");
        tblpengeluaran.setModel(tb);
        try{
            //m4ngwmbil data dari database
            rs=stm.executeQuery("Select * from pengeluaran");
            while (rs.next()){
                tb.addRow(new Object[]{
                    rs.getString("ID_Pengeluaran"),
                    rs.getString("Tanggal_Pengeluaran"),
                    rs.getString("Tagihan_Listrik"),
                    rs.getString("Tagihan_Air"),
                    rs.getString("Kebutuhan_Fasilitas"),
                    rs.getString("Total"),
                });
            }
              
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "data gagal ditampilkan" + e.getMessage());
            e.printStackTrace();
        }
    }
 
 public void koneksimysql(){
    try{
        String url="jdbc:mysql://localhost/koswijayanti";
        String user="root";
        String pass="";
        Class.forName("com.mysql.jdbc.Driver");
        conn = (Connection) DriverManager.getConnection(url, user, pass);
        stm = (com.mysql.jdbc.Statement) conn.createStatement();
      
    }catch (Exception e){
        System.err.println("koneksi Gagal"+e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel = new javax.swing.JScrollPane();
        tblpengeluaran = new javax.swing.JTable();
        logo = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        penyewa = new javax.swing.JLabel();
        kamar = new javax.swing.JLabel();
        transaksi = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tagihanair = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtno = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtlistrik = new javax.swing.JTextField();
        txtAir = new javax.swing.JTextField();
        txtfasilitas = new javax.swing.JTextField();
        btnclear = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        LOGO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setPreferredSize(new java.awt.Dimension(452, 402));

        tblpengeluaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanggal Pengeluaran", "Tagihan Listrik", "Tagihan Air", "Kebutuhan Fasilitas"
            }
        ));
        tblpengeluaran.setSelectionBackground(new java.awt.Color(153, 51, 0));
        tblpengeluaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpengeluaranMouseClicked(evt);
            }
        });
        panel.setViewportView(tblpengeluaran);

        jPanel1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 590, 370));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/zzzz.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -100, -1, -1));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/ooo.png"))); // NOI18N
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        penyewa.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        penyewa.setForeground(new java.awt.Color(255, 255, 255));
        penyewa.setText("Penyewa");
        penyewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penyewaMouseClicked(evt);
            }
        });
        jPanel1.add(penyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        kamar.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        kamar.setForeground(new java.awt.Color(255, 255, 255));
        kamar.setText("Kamar");
        kamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kamarMouseClicked(evt);
            }
        });
        jPanel1.add(kamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        transaksi.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        transaksi.setForeground(new java.awt.Color(255, 255, 255));
        transaksi.setText("Transaksi");
        transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiMouseClicked(evt);
            }
        });
        jPanel1.add(transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, -1, -1));

        login.setFont(new java.awt.Font("Times New Roman", 1, 35)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/yyy.png"))); // NOI18N
        login.setText("Admin");
        login.setMaximumSize(new java.awt.Dimension(137, 37));
        login.setMinimumSize(new java.awt.Dimension(137, 37));
        login.setPreferredSize(new java.awt.Dimension(137, 37));
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, 170, 70));

        judul1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        judul1.setForeground(new java.awt.Color(153, 51, 0));
        judul1.setText("DATA PENGELUARAN");
        judul1.setMaximumSize(new java.awt.Dimension(49, 49));
        judul1.setMinimumSize(new java.awt.Dimension(268, 49));
        judul1.setPreferredSize(new java.awt.Dimension(268, 49));
        jPanel1.add(judul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 430, 90));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("Nomor Pengeluaran");
        jLabel1.setMaximumSize(new java.awt.Dimension(147, 26));
        jLabel1.setMinimumSize(new java.awt.Dimension(147, 26));
        jLabel1.setPreferredSize(new java.awt.Dimension(147, 26));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 230, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("Tagihan Listrik");
        jLabel2.setMaximumSize(new java.awt.Dimension(147, 26));
        jLabel2.setMinimumSize(new java.awt.Dimension(147, 26));
        jLabel2.setPreferredSize(new java.awt.Dimension(147, 26));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 170, -1));

        tagihanair.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        tagihanair.setForeground(new java.awt.Color(102, 51, 0));
        tagihanair.setText("Tagihan Air");
        tagihanair.setMaximumSize(new java.awt.Dimension(147, 26));
        tagihanair.setMinimumSize(new java.awt.Dimension(147, 26));
        tagihanair.setPreferredSize(new java.awt.Dimension(147, 26));
        jPanel1.add(tagihanair, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Kebutuhan Fasilitas");
        jLabel3.setMaximumSize(new java.awt.Dimension(147, 26));
        jLabel3.setMinimumSize(new java.awt.Dimension(147, 26));
        jLabel3.setPreferredSize(new java.awt.Dimension(147, 26));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, 220, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("Tanggal Pengeluaran");
        jLabel6.setMaximumSize(new java.awt.Dimension(147, 26));
        jLabel6.setMinimumSize(new java.awt.Dimension(147, 26));
        jLabel6.setPreferredSize(new java.awt.Dimension(147, 26));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 230, -1));

        txtno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoActionPerformed(evt);
            }
        });
        txtno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnoKeyTyped(evt);
            }
        });
        jPanel1.add(txtno, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 260, 380, -1));

        btnsimpan.setBackground(new java.awt.Color(153, 51, 0));
        btnsimpan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("Simpan");
        btnsimpan.setPreferredSize(new java.awt.Dimension(121, 35));
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 620, 150, 50));

        btntambah.setBackground(new java.awt.Color(153, 51, 0));
        btntambah.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btntambah.setForeground(new java.awt.Color(255, 255, 255));
        btntambah.setText("...");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        jPanel1.add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 510, 50, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("DATA PENGELUARAN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        txtlistrik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtlistrik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlistrikActionPerformed(evt);
            }
        });
        txtlistrik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlistrikKeyTyped(evt);
            }
        });
        jPanel1.add(txtlistrik, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 360, 380, -1));

        txtAir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirActionPerformed(evt);
            }
        });
        jPanel1.add(txtAir, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 410, 380, -1));

        txtfasilitas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtfasilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfasilitasActionPerformed(evt);
            }
        });
        txtfasilitas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfasilitasKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfasilitasKeyReleased(evt);
            }
        });
        jPanel1.add(txtfasilitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 460, 380, -1));

        btnclear.setBackground(new java.awt.Color(153, 51, 0));
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 620, 150, 50));

        txtcari.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        txtcari.setPreferredSize(new java.awt.Dimension(6, 20));
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });
        jPanel1.add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 590, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("Total");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, -1, 40));

        txttotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txttotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttotalKeyReleased(evt);
            }
        });
        jPanel1.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 510, 320, 30));

        btnupdate.setBackground(new java.awt.Color(153, 51, 0));
        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 620, 150, 50));

        jDateChooser1.setBackground(new java.awt.Color(254, 240, 235));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 310, 380, 30));

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Template 1 (fix).png"))); // NOI18N
        jPanel1.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
     koneksimysql();
        String Tampilan = "yyyy-MM-dd";
        SimpleDateFormat dateFormat = new SimpleDateFormat(Tampilan);
        String tanggalpengeluaran = String.valueOf(dateFormat.format(jDateChooser1.getDate()));
        
        String airText = LOGO.getText();
        double airValue = 0.0; // Nilai default jika konversi gagal

        try {
        airValue = Double.parseDouble(airText);
        } catch (NumberFormatException e) {
        // Penanganan kesalahan jika konversi gagal
        // Misalnya, memberikan nilai default atau menampilkan pesan kesalahan kepada pengguna
        }

    try {
    String sql = "INSERT INTO pengeluaran VALUES ("
                + "'" + txtno.getText() + "',"
                + "'" + tanggalpengeluaran + "',"
                + "'" + txtlistrik.getText() + "',"
                + "'" + txtAir.getText() + "',"
                + "'" + txtfasilitas.getText() + "',"
                + "'" + txttotal.getText() + "')";

    psht = conn.prepareStatement(sql);
    psht.executeUpdate();
    koneksimysql();
    JOptionPane.showMessageDialog(null, "Data Telah Tersimpan");
} catch (Exception e) {
    e.printStackTrace();
}

         tampiltabel();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void txtAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirActionPerformed

    private void txtfasilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfasilitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfasilitasActionPerformed

    private void kamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kamarMouseClicked
this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_kamarMouseClicked

    private void txtlistrikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlistrikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlistrikActionPerformed

    private void txtfasilitasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfasilitasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfasilitasKeyPressed

    private void txtfasilitasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfasilitasKeyReleased
        // TODO add your handling code here 

 
    }//GEN-LAST:event_txtfasilitasKeyReleased

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        koneksimysql();
        String Tampilan = "yyyy-MM-dd";
        SimpleDateFormat dateFormat = new SimpleDateFormat(Tampilan);
        String tanggalpengeluaran = String.valueOf(dateFormat.format(jDateChooser1.getDate()));
       
       try {
    String sql = "UPDATE pengeluaran SET ID_Pengeluaran = ?, Tanggal_Pengeluaran = ?, Tagihan_Listrik = ?, Tagihan_Air = ?, Kebutuhan_Fasilitas = ?, Total = ? WHERE ID_Pengeluaran = ?";
    PreparedStatement psht = conn.prepareStatement(sql);

    psht.setString(1, txtno.getText());
    psht.setString(2, tanggalpengeluaran);
    psht.setString(3, txtlistrik.getText());
    psht.setString(4, txtAir.getText());
    psht.setString(5, txtfasilitas.getText());
    psht.setString(6, txttotal.getText());
    psht.setString(7, txtno.getText());

    psht.executeUpdate();
    JOptionPane.showMessageDialog(null, "Data berhasil diperbarui");
} catch (Exception e) {
    e.printStackTrace();
}

        tampiltabel();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void txtlistrikKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlistrikKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtlistrikKeyTyped

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        // TODO add your handling code here:
          DefaultTableModel obj = (DefaultTableModel) tblpengeluaran.getModel();
        TableRowSorter<DefaultTableModel> obj1 = new TableRowSorter<>(obj);
        tblpengeluaran.setRowSorter(obj1);
        obj1.setRowFilter(RowFilter.regexFilter(txtcari.getText()));
    }//GEN-LAST:event_txtcariKeyReleased

    private void txtnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoActionPerformed

    private void txtnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoKeyTyped

    private void tblpengeluaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpengeluaranMouseClicked
    int tabel = tblpengeluaran.getSelectedRow();
    txtno.setText((String) tblpengeluaran.getValueAt(tabel, 0));
     String tanggalPengeluaran = (String) tblpengeluaran.getValueAt(tabel, 1);
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date tanggal;
            try {
                tanggal = dateFormat.parse(tanggalPengeluaran);
                jDateChooser1.setDate(tanggal);
        } catch (Exception e) {
            e.printStackTrace();
        }
    txtlistrik.setText((String) tblpengeluaran.getValueAt(tabel, 2));        
    txtAir.setText((String) tblpengeluaran.getValueAt(tabel, 3));        
    txtfasilitas.setText((String) tblpengeluaran.getValueAt(tabel, 4));        
    txttotal.setText((String) tblpengeluaran.getValueAt(tabel, 5));            
    }//GEN-LAST:event_tblpengeluaranMouseClicked

    private void txttotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttotalKeyReleased
    int a = Integer.parseInt(txtlistrik.getText());
    int b = Integer.parseInt(txtAir.getText());
    int c = Integer.parseInt(txtfasilitas.getText());
    
    int total = a+b+c;
    txttotal.setText(String.valueOf(total));
    }//GEN-LAST:event_txttotalKeyReleased

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
    txtno.setText("");   
    jDateChooser1.setDate(null);
    txtlistrik.setText("");
    txtAir.setText("");
    txtfasilitas.setText("");
    txttotal.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
    int total = Integer.parseInt(txtlistrik.getText()) + Integer.parseInt(txtAir.getText()) + Integer.parseInt(txtfasilitas.getText());
    txttotal.setText(""+total); 
    }//GEN-LAST:event_btntambahActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
    this.setVisible(false);
    new Beranda().setVisible(true);
    }//GEN-LAST:event_homeMouseClicked

    private void penyewaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penyewaMouseClicked
    this.setVisible(false);
    new Penyewa().setVisible(true);    
    }//GEN-LAST:event_penyewaMouseClicked

    private void transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseClicked
    this.setVisible(false);
    new Data_Transaksi().setVisible(true);
    }//GEN-LAST:event_transaksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPengeluaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel home;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel kamar;
    private javax.swing.JLabel login;
    private javax.swing.JLabel logo;
    private javax.swing.JScrollPane panel;
    private javax.swing.JLabel penyewa;
    private javax.swing.JLabel tagihanair;
    private javax.swing.JTable tblpengeluaran;
    private javax.swing.JLabel transaksi;
    private javax.swing.JTextField txtAir;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtfasilitas;
    private javax.swing.JTextField txtlistrik;
    private javax.swing.JTextField txtno;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

   
}
